/*
* generated by Xtext
*/
package zarnekow.hello;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HelloDSLStandaloneSetup extends HelloDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new HelloDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

