/*
 * generated by Xtext
 */
package zarnekow.hello;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HelloDSLRuntimeModule extends zarnekow.hello.AbstractHelloDSLRuntimeModule {

}
