/*
 * generated by Xtext
 */
package zarnekow.goodbye.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import zarnekow.goodbye.ui.internal.GoodbyeDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GoodbyeDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GoodbyeDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GoodbyeDSLActivator.getInstance().getInjector(GoodbyeDSLActivator.ZARNEKOW_GOODBYE_GOODBYEDSL);
	}
	
}
