/**
 * generated by Xtext
 */
package zarnekow.hello.validation;

import zarnekow.hello.validation.AbstractHelloDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class HelloDSLValidator extends AbstractHelloDSLValidator {
}
