/*
 * generated by Xtext
 */
package zarnekow.hello.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HelloDSLUiModule extends zarnekow.hello.ui.AbstractHelloDSLUiModule {
	public HelloDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
