/*
 * generated by Xtext
 */
package zarnekow.goodbye.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GoodbyeDSLUiModule extends zarnekow.goodbye.ui.AbstractGoodbyeDSLUiModule {
	public GoodbyeDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
