/*
 * generated by Xtext
 */
package zarnekow.goodbye;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GoodbyeDSLRuntimeModule extends zarnekow.goodbye.AbstractGoodbyeDSLRuntimeModule {

}
