/*
* generated by Xtext
*/
package zarnekow.goodbye;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GoodbyeDSLStandaloneSetup extends GoodbyeDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new GoodbyeDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		// If we want to tightly couple this language to the HelloDSL, we could trigger
		// the HelloDSLStandaloneSetup here
//		HelloDSLStandaloneSetup.doSetup();
		return super.createInjectorAndDoEMFRegistration();
	}
}

