/*
* generated by Xtext
*/
package zarnekow.hello.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import zarnekow.hello.services.HelloDSLGrammarAccess;

public class HelloDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HelloDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected zarnekow.hello.parser.antlr.internal.InternalHelloDSLParser createParser(XtextTokenStream stream) {
		return new zarnekow.hello.parser.antlr.internal.InternalHelloDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Enter";
	}
	
	public HelloDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HelloDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
