/*
 * generated by Xtext
 */
package zarnekow.hello.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import zarnekow.hello.ui.internal.HelloDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HelloDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HelloDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HelloDSLActivator.getInstance().getInjector(HelloDSLActivator.ZARNEKOW_HELLO_HELLODSL);
	}
	
}
