/*
* generated by Xtext
*/
package zarnekow.goodbye.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import zarnekow.goodbye.services.GoodbyeDSLGrammarAccess;

public class GoodbyeDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private GoodbyeDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected zarnekow.goodbye.ui.contentassist.antlr.internal.InternalGoodbyeDSLParser createParser() {
		zarnekow.goodbye.ui.contentassist.antlr.internal.InternalGoodbyeDSLParser result = new zarnekow.goodbye.ui.contentassist.antlr.internal.InternalGoodbyeDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGoodbyeAccess().getGroup(), "rule__Goodbye__Group__0");
					put(grammarAccess.getLeaveAccess().getFarewellsAssignment(), "rule__Leave__FarewellsAssignment");
					put(grammarAccess.getGoodbyeAccess().getHelloAssignment_1(), "rule__Goodbye__HelloAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			zarnekow.goodbye.ui.contentassist.antlr.internal.InternalGoodbyeDSLParser typedParser = (zarnekow.goodbye.ui.contentassist.antlr.internal.InternalGoodbyeDSLParser) parser;
			typedParser.entryRuleLeave();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GoodbyeDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GoodbyeDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
