/*
* generated by Xtext
*/
package zarnekow.goodbye.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GoodbyeDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("zarnekow/goodbye/parser/antlr/internal/InternalGoodbyeDSL.tokens");
	}
}
