/*
* generated by Xtext
*/
package zarnekow.hello.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import zarnekow.hello.services.HelloDSLGrammarAccess;

public class HelloDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private HelloDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected zarnekow.hello.ui.contentassist.antlr.internal.InternalHelloDSLParser createParser() {
		zarnekow.hello.ui.contentassist.antlr.internal.InternalHelloDSLParser result = new zarnekow.hello.ui.contentassist.antlr.internal.InternalHelloDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getHelloAccess().getGroup(), "rule__Hello__Group__0");
					put(grammarAccess.getEnterAccess().getGreetingsAssignment(), "rule__Enter__GreetingsAssignment");
					put(grammarAccess.getHelloAccess().getNameAssignment_1(), "rule__Hello__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			zarnekow.hello.ui.contentassist.antlr.internal.InternalHelloDSLParser typedParser = (zarnekow.hello.ui.contentassist.antlr.internal.InternalHelloDSLParser) parser;
			typedParser.entryRuleEnter();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public HelloDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HelloDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
