/*
 * generated by Xtext
 */
package zarnekow.hello.ui.contentassist

import zarnekow.hello.ui.contentassist.AbstractHelloDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HelloDSLProposalProvider extends AbstractHelloDSLProposalProvider {
}
