/*
 * generated by Xtext
 */
package zarnekow.goodbye.ui.contentassist

import zarnekow.goodbye.ui.contentassist.AbstractGoodbyeDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GoodbyeDSLProposalProvider extends AbstractGoodbyeDSLProposalProvider {
}
