/**
 * generated by Xtext
 */
package zarnekow.goodbye.validation;

import zarnekow.goodbye.validation.AbstractGoodbyeDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GoodbyeDSLValidator extends AbstractGoodbyeDSLValidator {
}
